package calibur.core.utils;

/**
 * author : J.Chou
 * e-mail : who_know_me@163.com
 * time   : 2018/11/22 11:13 PM
 * version: 1.0
 * description:
 */
public interface ISharedPreferencesKeys {
  String MOBILE_TOKEN = "Authorization";
  String EDITOR_PAGE_TEMPLATE = "EDITOR_PAGE_TEMPLATE";
  String IMAGE_DETAIL_PAGE_TEMPLATE = "IMAGE_DETAIL_PAGE_TEMPLATE";
  String BOOKMARKS_PAGE_TEMPLATE = "BOOKMARKS_PAGE_TEMPLATE";
  String NOTICE_PAGE_TEMPLATE = "NOTICE_PAGE_TEMPLATE";
  String REVIEW_PAGE_TEMPLATE = "REVIEW_PAGE_TEMPLATE";
  String POST_DETAIL_PAGE_TEMPLATE = "POST_DETAIL_PAGE_TEMPLATE";
  String NOTIFICATION_PAGE_TEMPLATE = "NOTIFICATION_PAGE_TEMPLATE";
  String TRANSACTIONS_PAGE_TEMPLATE = "TRANSACTIONS_PAGE_TEMPLATE";
}
